### ISSUE TITLE
Add some screenshots

### ISSUE THREAD

**Issue by twiecki** [evdoxiataka/imd#6]
I think people would get a much better idea of what this interesting project is about if there were more visuals in terms of screenshots, videos, or NBs.

**Comment by evdoxiataka** [comment]
Thanks for the comment, I will do! Just to let you know that the latest version of the tool is on the "[ipme](https://github.com/evdoxiataka/ipme)" repository, and this one is no longer used. Sorry for the confusion. I will remove this one, as other people might get confused.
